0 hero_ability
"old ability" "old value"
"new ability" "new value"

1 pudge_flesh_heap
"flesh_heap_strength_buff_amount"	"1.0 1.5 2.0 2.5"
"flesh_heap_strength_buff_amount"	"0.3 0.7 1.1 1.5"

2 silencer_glaives_of_wisdom
"intellect_damage_pct"	"35 50 65 80"
"intellect_damage_pct"	"25 30 35 40"

3 earthshaker_echo_slam
"echo_slam_echo_search_range" "575"
"echo_slam_echo_search_range" "300"

4 bloodseeker_thirst
"min_bonus_pct"				"75"
"min_bonus_pct"				"60"

"bonus_movement_speed"		"16 24 32 40"
"bonus_movement_speed"		"12 18 24 30"

"bonus_damage"				"16 24 32 40"
"bonus_damage"				"12 18 24 30"
5 axe_counter_helix
"AbilityDamage"				"70 95 115 140"


